### ISSUE TITLE
Support for further autojumpers

### ISSUE THREAD

**Issue by matu3ba** [nvim-telescope/telescope-z.nvim#1]
Would you consider to support further autojumpers like [zoxide](https://github.com/ajeetdsouza/zoxide) ?

**Comment by delphinus** [comment]
You can customize `cmd` to launch with z-compatibles.

```lua
lua require'telescope'.extensions.z.list{cmd = {'zoxide', 'query', 'sl'}}
```

(I'm not a `zoxide` user, so change to a suitable `cmd` you prefer.)

**Comment by matu3ba** [comment]
Ah, sorry. My bad. Closing.

**Comment by matu3ba** [comment]
`require'telescope'.load_extension'z'{ cmd = {'zoxide', 'query', '-sl'} }` did not work and neither did `require'telescope'.load_extension'z'{ cmd = {'zq', '-sl'} }`.

I get the error
```txt
E5108: Error executing lua /home/misterspoon/.config/nvim/lua/_telesc.lua:17: attempt to call a table value
```

**Comment by Conni2461** [comment]
It should be something like `cmd = { vim.o.shell, '-c', 'zoxide query -sl' }` if i get his code correctly.

Can i make a suggestion as not maintainer of that repo :) it would be cool if it is possible to configure that in
```lua
telescope.setup {
  extensions = {
    z = {
      cmd = { vim.o.shell, '-c', 'zoxide query -sl' }
    }
  }
}
```
Similar to what frecency does with the configuration. That way it doesn't have to be specified every time when calling `:Telescope z list`

And a readme entry if you decide to do something like this :)

**Comment by matu3ba** [comment]
> It should be something like `cmd = { vim.o.shell, '-c', 'zoxide query -sl' }` if i get his code correctly.

`require'telescope'.load_extension'z'{ cmd = { vim.o.shell, '-c', 'zoxide query -sl' } }` does not work either
```txt
E5108: Error executing lua /home/misterspoon/.config/nvim/lua/_telesc.lua:18: attempt to call a table value
```

**Comment by Conni2461** [comment]
Oh not with load_extension. Its an opt for list:
```lua
:lua require'telescope'.extensions.z.list{ cmd = { vim.o.shell, '-c', 'zoxide query -sl' } }
```

My idea would make one time configuration work

**Comment by matu3ba** [comment]
Hinting that it should be used in a keymap would have been useful.

The following works:
`vim.api.nvim_set_keymap('n', '<leader>tezl',   [[<cmd>lua require'telescope'.extensions.z.list{ cmd = { vim.o.shell, '-c', 'zoxide query -sl' } }<CR>]], { noremap = true, silent = true })
`

**Comment by delphinus** [comment]
Now it is put on README (#3). Close this.
