### ISSUE TITLE
 beginner question

### ISSUE THREAD

**Issue by molleweide** [nvim-telescope/telescope-z.nvim#10]
When I run `:Telescope z list` should I expect it to show the same output as if I run `z` in the terminal? 
Currently nothing is showing but I am not sure what to expect.

I am learning to make configs in lua and I have been using fasd and fzf previously from a dotfiles repo that I cloned.
Can I use this plugin with fasd if fasd is aliased to `z`?
I see that you mention quote `z or it'd compatibles` in the readme but I am kind of a beginner with this so I don't really 
know what that statement implies. That is why I am asking.

**Comment by khalidchawtany** [comment]
Same issue here :(

**Comment by delphinus** [comment]
Sorry for late. `:Telescope z list` runs `$SHELL -c 'z -l'` in the background, and parse the output such as below.

```sh
$ z -l
1234.0   /path/to/foo
123.01   /path/to/bar
120.01   /path/to/foobar
1.0012   /path/to/barfoo

...
```

`z -l` shows all entries sorted by the score that means you visit more frequently, probably. `rupa/z or its compatibles` means the tool you use should have the way to print the similar outputs -- in acurate, it should match `([%.%d]+)%s+(.+)` (Lua regexp).

There is an option to set the compatible ones.

```lua
require'telescope'.extensions.z.list{
  cmd = {'bash', '-c', 'z-like-tool-you-like', '-l'},
}
```

This expects the output from `z-like-tool-you-like -l` should match the regexp above. I'm not familiar with `fasd`, so I do not know it can print such outputs.

**Comment by delphinus** [comment]
Maybe it seems `fasd -d` is the one you want……? Then you can use it with the code below.

```lua
require'telescope'.extensions.z.list{
  cmd = {'bash', '-c', 'fasd', '-d'},
}
```

**Comment by delphinus** [comment]
Re-open here if not solved yet.
