### ISSUE TITLE
Results are shown in stderr rather than stdout

### ISSUE THREAD

**Issue by petobens** [nvim-telescope/telescope-z.nvim#12]
Since the `z` module is not in my PATH in order to run the `z` executable I do:
```lua
:lua require('telescope').extensions.z.list({cmd = {'bash', '-c', 'source /usr/share/z/z.sh && _z -l'}})
```
The output of [this line](https://github.com/nvim-telescope/telescope-z.nvim/blob/main/lua/telescope/_extensions/z_builtin.lua#L76), which  gets the command output, is:
```
{}
1
{ "0.43876    /home/pedro/Desktop/asdad", "0.43876    /home/pedro/Desktop/bigdata-workshop-es", "0.43876    /home/pedro/Desktop/bigquery", "0.43876    /home/pedro/Desktop/fury_fda-python/commands", "0.43876    /h
ome/pedro/git-repos/forks/semshi/rplugin/python3/semshi", "0.43876    /home/pedro/git-repos/private/dotfiles/arch/config/rofi", "0.43876    /home/pedro/git-repos/private/dotfiles/nvim/cache/Arch/tmp/swap", "0.438
76    /home/pedro/git-repos/private/dotfiles/R", "0.43876    /home/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/kristijanhusak/vim-dadbod_async-query", "0.43876    /home/pedro/git-repos/teaching/b
igdata-workshop-es/airflow", "0.43876    /home/pedro/git-repos/teaching/bigdata-workshop-es/code/docker/script", "0.43876    /home/pedro/git-repos/teaching/introduccion-ml-aplicado/ejercicios", "0.43876    /home/
pedro/git-repos/work/trafilea/ds-project-mbat/modules/mbat/bumblebee/data/store", "0.43876    /home/pedro/git-repos/work/trafilea/ds-project-mbat/modules/mbat/bumblebee/learn" }
```
which implies that the `_z` executable output  is thrown into the stderr rather than the stdout as per https://github.com/nvim-telescope/telescope.nvim/blob/f262e7d56d37625613c5de0df5a933cccacf13c5/lua/telescope/utils.lua#L426 .

Any pointers about what's going on? Thanks in advance

**Comment by delphinus** [comment]
@petobens  Sorry for a late response. You are using [rupa/z][]? Then, `_z()` is an internal function, and it sends its output to stderr intentionally (See [here][]). [rupa/z defines `z()`][z] for usual use.

[rupa/z]: https://github.com/rupa/z
[here]: https://github.com/rupa/z/blob/b82ac78a2d4457d2ca09973332638f123f065fd1/z.sh#L159
[z]: https://github.com/rupa/z/blob/b82ac78a2d4457d2ca09973332638f123f065fd1/z.sh#L227

```lua
:lua require('telescope').extensions.z.list({cmd = {'bash', '-c', 'source /usr/share/z/z.sh && z -l'}})
```

You can get expected results with commands above, I think.
