### ISSUE TITLE
List returning empty

### ISSUE THREAD

**Issue by cj** [nvim-telescope/telescope-z.nvim#14]
Hi - the list is returning empty in Telescope, but doing `z -l` in the terminal shows results:

<img width="853" alt="image" src="https://user-images.githubusercontent.com/1819/185686478-68a8edf4-de46-4562-a52e-831124d40bce.png">

Let me know what debug information I can give you!

**Comment by delphinus** [comment]
Hmm, it seems that Neovim executes `z` differently from your way in the shell. telescope-z uses `'shell'` for the shell to launch `z -l`. If you set `set shell=zsh`, telescope-z launches `zsh -c 'z -l'` in default. So I want to see your

1. `'shell'`. Show me your `set shell?` output.
2. telescope-z settings in your `init.lua`.

**Comment by cj** [comment]
<img width="113" alt="image" src="https://user-images.githubusercontent.com/1819/185827892-d562992f-2f2f-4f80-b458-543fec49067c.png">
<img width="513" alt="image" src="https://user-images.githubusercontent.com/1819/185827946-088f91bd-bee8-4757-b875-851c7654f0b9.png">

**Comment by delphinus** [comment]
They seem correct.

1. Can you get a valid response by `zsh -c 'z -l'` in your shell?
   * Attempts in Neovim's shell (`:term`) are more better.
3. Try `:lua require'telescope'.extensions.z.list { cmd = { 'zsh', '-c', 'z -l' } }`

**Comment by cj** [comment]
@delphinus it looks like the issue was I need to do `ln -s ~/.zshrc ~/.zshenv`. I have it working now, thank you for your help!!
